import json
import pickle

import faiss
import numpy as np

from sentence_transformers import SentenceTransformer
import os

CURRENT_DIR = os.path.dirname(os.path.abspath(__file__))

MODEL_NAME = "BAAI/bge-large-en-v1.5"

encoder = None


def load_encoder():

    global encoder

    if encoder is None:

        print("Loading BGE encoder...")

        encoder = SentenceTransformer(
            MODEL_NAME,
            device="cuda"
        )

        print("BGE encoder loaded successfully.")

    return encoder



print("Loading FAISS index...")

index = faiss.read_index(
    os.path.join(CURRENT_DIR, "cgga.index")
)

print("FAISS index loaded.")



# LOAD CGGA DOCUMENTS
with open(
    os.path.join(CURRENT_DIR, "documents.pkl"),
    "rb"
) as f:

    documents = pickle.load(f)



# LOAD CGGA METADATA
with open(
    os.path.join(CURRENT_DIR, "metadata.pkl"),
    "rb"
) as f:

    metadata = pickle.load(f)

print(f"Loaded {len(documents)} CGGA patient documents.")
print(f"Loaded {len(metadata)} metadata records.")



def build_final_query(query, semantic_findings):
    """
    Combines the clinical query generated by Component 1
    with additional semantic findings before retrieval.

    Parameters
    ----------
    query : str
        Clinical query produced by Component 1

    semantic_findings : list[str]
        Interpreted imaging findings

    Returns
    -------
    str
        Final retrieval query
    """

    final_query = query.strip()

    if len(semantic_findings) > 0:

        final_query += "\n\nClinical Imaging Findings:\n"

        for finding in semantic_findings:
            final_query += f"- {finding}\n"

    return final_query


# INTERPRET MRI FEATURES
def interpret_metrics(features):
    """
    Converts numerical MRI features into semantic findings
    that improve retrieval quality.

    Parameters
    ----------
    features : dict

    Returns
    -------
    list[str]
    """

    findings = []

    
    if features["et_tc_ratio"] > 0.8:

        findings.append(
            "Predominantly enhancing tumor core"
        )


    if features["ncr_tc_ratio"] > 0.4:

        findings.append(
            "Significant necrotic component"
        )


    if features["ed_wt_ratio"] > 0.7:

        findings.append(
            "Extensive peritumoral edema"
        )


    if features.get("enhancement_ratio", 0) > 10:

        findings.append(
            "Marked contrast enhancement"
        )


    if features.get("sphericity", 0) > 0.8:

        findings.append(
            "Relatively regular tumor morphology"
        )

    if features.get("solidity", 0) < 0.5:

        findings.append(
            "Irregular infiltrative tumor pattern"
        )


    wt_volume = features.get(
        "wt_volume_cc",
        0
    )

    if wt_volume > 40:

        findings.append(
            "Large tumor burden"
        )

    elif wt_volume > 20:

        findings.append(
            "Moderate tumor burden"
        )

    else:

        findings.append(
            "Small tumor burden"
        )

    return findings


# RUN RAG FOR SINGLE PATIENT
def run_rag(features, query):
    
    """
    Performs RAG retrieval for one uploaded MRI.

    Parameters
    ----------
    features : dict
        Vision features from Component 1

    query : str
        Clinical query from Component 1

    Returns
    -------
    dict
        RAG output for Component 3
    """
    encoder = load_encoder()

    semantic_findings = interpret_metrics(features)


    final_query = build_final_query(
        query,
        semantic_findings
    )


    query_embedding = encoder.encode(
        final_query,
        normalize_embeddings=True
    )

    query_embedding = np.asarray(
        query_embedding,
        dtype=np.float32
    )


    scores, indices = index.search(
        query_embedding.reshape(1, -1),
        5
    )

    retrieved_patients = []

    idh_counts = {}
    mgmt_counts = {}

    os_values = []


    # PROCESS TOP 5 PATIENTS
    for rank, idx in enumerate(indices[0], start=1):

        meta = metadata[idx]

        similarity = float(scores[0][rank - 1])

        retrieved_patients.append(

            {
                "rank": rank,

                "similarity": similarity,

                "confidence": round(
                    similarity * 100,
                    2
                ),

                "metadata": meta
            }

        )

        os_values.append(
            float(meta["os_days"])
        )

        idh = meta.get(
            "idh",
            "Unknown"
        )

        mgmt = meta.get(
            "mgmt",
            "Unknown"
        )

        idh_counts[idh] = (
            idh_counts.get(idh, 0) + 1
        )

        mgmt_counts[mgmt] = (
            mgmt_counts.get(mgmt, 0) + 1
        )


    # COHORT STATISTICS
    dominant_idh = max(
        idh_counts,
        key=idh_counts.get
    )

    dominant_mgmt = max(
        mgmt_counts,
        key=mgmt_counts.get
    )

    avg_os = round(
        np.mean(os_values),
        1
    )

    avg_similarity = round(
        float(np.mean(scores[0])),
        4
    )

    avg_similarity_percent = round(
        avg_similarity * 100,
        2
    )

    top_patient = retrieved_patients[0]["metadata"]

    # RETURN RESULT
    return {

        "vision_metrics": features,

        "semantic_findings": semantic_findings,

        "cohort_summary": {

            "idh_distribution": idh_counts,

            "mgmt_distribution": mgmt_counts,

            "dominant_idh": dominant_idh,

            "dominant_mgmt": dominant_mgmt,

            "average_os_days": avg_os,

            "average_similarity": avg_similarity,

            "average_similarity_percent":
                avg_similarity_percent
        },

        "top_match": {

            "patient_id":
                top_patient["patient_id"],

            "idh":
                top_patient["idh"],

            "mgmt":
                top_patient["mgmt"],

            "os_days":
                top_patient["os_days"]
        },

        "retrieved_patients":
            retrieved_patients
    }
import gc
import torch


def unload_encoder():

    global encoder

    if encoder is not None:

        del encoder
        encoder = None

    gc.collect()

    if torch.cuda.is_available():
        torch.cuda.empty_cache()

    print("BGE unloaded.")